"use client";
import { useState } from "react";

const orgs = [
  {id:"nrif",name:"NCST / NRIF",type:"Grant funding body",sources:["RIGMS","Historical Applications","Eligibility Rules"],mode:"Connected"},
  {id:"university",name:"University Research Office",type:"Institutional research office",sources:["Institutional Repository","Researcher Directory","DOI Metadata"],mode:"Local-first"},
  {id:"institute",name:"Research Institute",type:"Research institute",sources:["Publication Database","Project Archive"],mode:"Local-first"}
];
const proposals = [
  {id:"NRIF-2026-014",title:"AI-based crop disease detection",status:"Review required",score:.94,duplicate:2},
  {id:"NRIF-2026-015",title:"Climate-smart irrigation analytics",status:"Ready for review",score:.98,duplicate:0},
  {id:"NRIF-2026-016",title:"Digital health early warning system",status:"Review required",score:.89,duplicate:1}
];

export default function Home(){
  const [org,setOrg]=useState(orgs[0]),[tab,setTab]=useState("overview"),[selected,setSelected]=useState(proposals[0]);
  const nav=[["overview","Overview"],["screening","Grant Screening"],["publications","Publication Reconciliation"],["review","Human Review"],["integrations","Integrations"]];
  return <main><aside><div className="brand"><span>AI</span><div><b>AI-SCREENING</b><small>Research Intelligence</small></div></div><div className="label">WORKSPACE</div>{nav.map(([id,label])=><button className={tab===id?"nav active":"nav"} onClick={()=>setTab(id)} key={id}>{label}</button>)}<div className="side-note"><small>AI-assisted, human-controlled</small><p>No automated funding decisions.</p></div></aside>
  <section className="content"><header><div><div className="eyebrow">ORGANIZATION WORKSPACE</div><h1>{org.name}</h1><p>{org.type} · <span className="status">● {org.mode}</span></p></div><select value={org.id} onChange={e=>setOrg(orgs.find(o=>o.id===e.target.value)!)}>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></header>
  {tab==="overview"&&<Overview org={org}/>}
  {tab==="screening"&&<Screening selected={selected} setSelected={setSelected}/>}
  {tab==="publications"&&<Publications/>}{tab==="review"&&<Review/>}{tab==="integrations"&&<Integrations org={org}/>}</section></main>
}
function Card({n,l}:{n:string,l:string}){return <div className="card"><b>{n}</b><span>{l}</span></div>}
function Panel({title,children}:{title:string,children:React.ReactNode}){return <div className="panel"><h3>{title}</h3>{children}</div>}
function Overview({org}:{org:any}){return <><div className="hero"><div><span className="pill">AI / ML PIPELINE</span><h2>From documents to evidence-backed review.</h2><p>Connect organizational data sources, run deterministic rules and ML analysis, then route every flag to a human reviewer.</p></div><div className="pipeline">{["Ingest","Extract","Analyze","Evidence","Human review"].map((x,i)=><div className="stage" key={x}><strong>0{i+1}</strong><span>{x}</span></div>)}</div></div><div className="cards"><Card n="3" l="Proposals in screening"/><Card n="7" l="Similarity candidates"/><Card n="4" l="Review queue"/><Card n="12" l="Publications reconciled"/></div><div className="grid"><Panel title="Connected data sources"><div className="sources">{org.sources.map((s:string)=><div className="source" key={s}><i>✓</i><span>{s}</span><em>Available</em></div>)}</div></Panel><Panel title="AI modules"><div className="modules">{["Document Intelligence","Eligibility Rules","Semantic Retrieval","Duplicate Detection","Entity Resolution","Explainability"].map(x=><span key={x}>● {x}</span>)}</div></Panel></div></>}
function Screening({selected,setSelected}:{selected:any,setSelected:any}){return <><div className="section-head"><div><div className="eyebrow">GRANT SCREENING</div><h2>Proposal screening workspace</h2></div><button className="primary">+ Upload proposal</button></div><div className="two"><Panel title="Screening queue">{proposals.map(p=><button className={selected.id===p.id?"row selected":"row"} onClick={()=>setSelected(p)} key={p.id}><span><b>{p.id}</b><small>{p.title}</small></span><strong>{Math.round(p.score*100)}%</strong></button>)}</Panel><div className="panel"><div className="doc-head"><div><span className="eyebrow">PROPOSAL</span><h3>{selected.title}</h3><small>{selected.id} · Synthetic demo record</small></div><span className="pill">{selected.status}</span></div><div className="checks">{[["Completeness","PASS","0.98"],["Eligibility","REVIEW","0.91"],["Duplicate candidate",selected.duplicate?"FLAG":"PASS",selected.duplicate?"0.94":"0.99"],["Text overlap",selected.duplicate?"FLAG":"PASS",selected.duplicate?"0.87":"0.99"]].map(x=><div className="check" key={x[0]}><span><b>{x[0]}</b><small>Evidence-backed analysis</small></span><strong>{x[1]} · {x[2]}</strong></div>)}</div><div className="evidence"><b>Evidence preview</b><p>Page 4 · chunk 8f2a91c1 — “The proposed model will classify maize leaf disease using…”</p><p>Page 7 · historical proposal NRIF-2024-118 — semantic similarity candidate.</p></div><div className="actions"><button>Open evidence</button><button>Send to review</button></div></div></div></>}
function Publications(){return <><div className="section-head"><div><div className="eyebrow">PUBLICATION RECONCILIATION</div><h2>Local-first synchronization</h2><p>International connectors are optional. Core reconciliation works with available local records.</p></div><button className="primary">Run reconciliation</button></div><div className="cards"><Card n="23" l="Local records"/><Card n="17" l="Matched"/><Card n="4" l="Metadata conflicts"/><Card n="2" l="Potentially missing"/></div><Panel title="Reconciliation candidates">{[["PUB-1042","AI in African agriculture","98.7%","MATCH"],["PUB-1077","Machine learning for rural health","93.4%","REVIEW"],["PUB-1091","Climate adaptation analytics","71.2%","CONFLICT"]].map(r=><div className="recon" key={r[0]}><div><b>{r[0]}</b><span>{r[1]}</span></div><strong>{r[2]}</strong><span className="pill">{r[3]}</span><button>Compare</button></div>)}</Panel></>}
function Review(){return <><div className="section-head"><div><div className="eyebrow">HUMAN REVIEW</div><h2>Evidence before decision</h2><p>AI produces flags and evidence; authorized staff make the final decision.</p></div></div><Panel title="Review queue"><div className="review-banner">Human validation required for every consequential screening decision.</div>{["NRIF-2026-014 · Duplicate candidate","NRIF-2026-016 · Eligibility criterion","PUB-1077 · Author entity match"].map((x,i)=><div className="review-row" key={x}><div><b>{x}</b><small>{["2 supporting sources","1 rule + page evidence","3 matched author fields"][i]}</small></div><button>Review evidence</button></div>)}</Panel></>}
function Integrations({org}:{org:any}){return <><div className="section-head"><div><div className="eyebrow">INTEGRATIONS</div><h2>{org.name}</h2><p>Configure connectors without changing the AI/ML core.</p></div><button className="primary">+ Add connector</button></div><div className="grid">{org.sources.map((s:string)=><div className="panel connector" key={s}><div><span className="connector-icon">↔</span><h3>{s}</h3><small>Connector ready for authorized data</small></div><span className="status">● Available</span><button>Configure</button></div>)}</div></>}
