"use client";
import { useState } from "react";

const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL || "http://localhost:8000";

const orgs = [
  {id:"nrif",name:"NCST / NRIF",type:"Grant funding body",sources:["RIGMS","Historical Applications","Eligibility Rules"],mode:"Connected"},
  {id:"university",name:"University Research Office",type:"Institutional research office",sources:["Institutional Repository","Researcher Directory","DOI Metadata"],mode:"Local-first"},
  {id:"institute",name:"Research Institute",type:"Research institute",sources:["Publication Database","Project Archive"],mode:"Local-first"}
];
const proposals = [
  {id:"NRIF-2026-014",title:"AI-based crop disease detection",status:"Review required",score:.94,duplicate:2},
  {id:"NRIF-2026-015",title:"Climate-smart irrigation analytics",status:"Ready for review",score:.98,duplicate:0},
  {id:"NRIF-2026-016",title:"Digital health early warning system",status:"Review required",score:.89,duplicate:1}
];

export default function Home(){
  const [org,setOrg]=useState(orgs[0]),[tab,setTab]=useState("overview"),[selected,setSelected]=useState(proposals[0]);
  const nav=[["overview","Overview"],["screening","Grant Screening"],["publications","Publication Reconciliation"],["review","Human Review"],["integrations","Integrations"]];
  return <main><aside><div className="brand"><span>AI</span><div><b>AI-SCREENING</b><small>Research Intelligence</small></div></div><div className="label">WORKSPACE</div>{nav.map(([id,label])=><button className={tab===id?"nav active":"nav"} onClick={()=>setTab(id)} key={id}>{label}</button>)}<div className="side-note"><small>AI-assisted, human-controlled</small><p>No automated funding decisions.</p></div></aside>
  <section className="content"><header><div><div className="eyebrow">ORGANIZATION WORKSPACE</div><h1>{org.name}</h1><p>{org.type} · <span className="status">● {org.mode}</span></p></div><select value={org.id} onChange={e=>setOrg(orgs.find(o=>o.id===e.target.value)!)}>{orgs.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></header>
  {tab==="overview"&&<Overview org={org}/>}
  {tab==="screening"&&<Screening selected={selected} setSelected={setSelected}/>}
  {tab==="publications"&&<Publications/>}{tab==="review"&&<Review/>}{tab==="integrations"&&<Integrations org={org}/>}</section></main>
}
function Card({n,l}:{n:string,l:string}){return <div className="card"><b>{n}</b><span>{l}</span></div>}
function Panel({title,children}:{title:string,children:React.ReactNode}){return <div className="panel"><h3>{title}</h3>{children}</div>}
function Overview({org}:{org:any}){return <><div className="hero"><div><span className="pill">AI / ML PIPELINE</span><h2>From documents to evidence-backed review.</h2><p>Connect organizational data sources, run deterministic rules and ML analysis, then route every flag to a human reviewer.</p></div><div className="pipeline">{["Ingest","Extract","Analyze","Evidence","Human review"].map((x,i)=><div className="stage" key={x}><strong>0{i+1}</strong><span>{x}</span></div>)}</div></div><div className="cards"><Card n="3" l="Proposals in screening"/><Card n="7" l="Similarity candidates"/><Card n="4" l="Review queue"/><Card n="12" l="Publications reconciled"/></div><div className="grid"><Panel title="Connected data sources"><div className="sources">{org.sources.map((s:string)=><div className="source" key={s}><i>✓</i><span>{s}</span><em>Available</em></div>)}</div></Panel><Panel title="AI modules"><div className="modules">{["Document Intelligence","Eligibility Rules","Semantic Retrieval","Duplicate Detection","Entity Resolution","Explainability"].map(x=><span key={x}>● {x}</span>)}</div></Panel></div></>}
function Screening({selected,setSelected}:{selected:any,setSelected:any}){
  const [result,setResult]=useState<any>(null),[uploading,setUploading]=useState(false),[error,setError]=useState("");
  async function handleUpload(file:File){
    setUploading(true);setError("");setResult(null);
    const body=new FormData();body.append("file",file);body.append("proposal_id",file.name.replace(/\\.[^.]+$/,""));
    try{const res=await fetch(`${API_BASE}/api/v1/grants/screen-document`,{method:"POST",body});const data=await res.json();if(!res.ok)throw new Error(data.detail||"Screening failed");setResult(data);}
    catch(e){setError(e instanceof Error?e.message:"Unable to connect to screening API.");}
    finally{setUploading(false);}
  }
  const active=result||selected;
  return <><div className="section-head"><div><div className="eyebrow">GRANT SCREENING</div><h2>Proposal screening workspace</h2><p>Upload a PDF or DOCX to run the real extraction and screening pipeline.</p></div><label className="primary upload">{uploading?"Analyzing…":"+ Upload proposal"}<input type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={e=>e.target.files?.[0]&&handleUpload(e.target.files[0])}/></label></div>
  {error&&<div className="error">{error}</div>}
  {result?<ResultView result={result}/>:<div className="two"><Panel title="Screening queue">{proposals.map(p=><button className={selected.id===p.id?"row selected":"row"} onClick={()=>setSelected(p)} key={p.id}><span><b>{p.id}</b><small>{p.title}</small></span><strong>{Math.round(p.score*100)}%</strong></button>)}</Panel><ProposalPreview proposal={active}/></div>}</>}
function ProposalPreview({proposal}:{proposal:any}){return <div className="panel"><div className="doc-head"><div><span className="eyebrow">DEMO PROPOSAL</span><h3>{proposal.title}</h3><small>{proposal.id} · Synthetic demo record</small></div><span className="pill">{proposal.status}</span></div><div className="checks">{[["Completeness","PASS","0.98"],["Eligibility","REVIEW","0.91"],["Duplicate candidate",proposal.duplicate?"FLAG":"PASS",proposal.duplicate?"0.94":"0.99"],["Text overlap",proposal.duplicate?"FLAG":"PASS",proposal.duplicate?"0.87":"0.99"]].map(x=><div className="check" key={x[0]}><span><b>{x[0]}</b><small>Demo evidence</small></span><strong>{x[1]} · {x[2]}</strong></div>)}</div><div className="evidence"><b>Connect the API to replace demo results</b><p>The upload action calls FastAPI, extracts the document with PyMuPDF/python-docx, applies the screening rules, similarity analysis and evidence generation.</p></div></div>}
function ResultView({result}:{result:any}){const ex=result.extraction||{}, checks=result.eligibility_checks||[];return <div className="panel"><div className="doc-head"><div><span className="eyebrow">LIVE SCREENING RESULT</span><h3>{ex.filename||result.proposal_id}</h3><small>{result.proposal_id} · {ex.page_count?ex.page_count+" pages · ":""}{ex.extraction_status}</small></div><span className="pill">Human review required</span></div><div className="cards mini"><Card n={`${result.completeness?.passed||0}/${result.completeness?.total||0}`} l="Completeness rules passed"/><Card n={`${(result.similarity_candidates||[]).length}`} l="Similarity candidates"/><Card n={`${(result.text_overlap||[]).length}`} l="Overlap sources"/><Card n={`${(result.evidence||[]).length}`} l="Evidence items"/></div><div className="checks">{checks.map((x:any)=><div className="check" key={x.criterion}><span><b>{x.criterion}</b><small>{x.evidence}</small></span><strong>{x.passed?"PASS":"FLAG"}</strong></div>)}</div><div className="evidence"><b>Evidence</b>{(result.evidence||[]).slice(0,6).map((x:any,i:number)=><p key={i}>{x.source_id} · {x.field} — {x.rationale}</p>)}</div></div>}
function Publications(){const [live,setLive]=useState<any[]>([]),[running,setRunning]=useState(false);async function run(){setRunning(true);try{const pairs=[["PUB-1042","AI in African agriculture","10.1234/demo","AI in African agriculture","10.1234/demo"],["PUB-1077","Machine learning for rural health",null,"Machine learning for rural health and community health",""],["PUB-1091","Climate adaptation analytics",null,"Climate adaptation analytics",null]];const out=[];for(const p of pairs){const res=await fetch(`${API_BASE}/api/v1/publications/reconcile-pair`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({left:{record_id:p[0],title:p[1],authors:["Demo Researcher"],doi:p[2],year:2026,source:"local-demo"},right:{record_id:p[0]+"-EXT",title:p[3],authors:["Demo Researcher"],doi:p[4],year:2026,source:"external-demo"}})});out.push(await res.json())}setLive(out)}finally{setRunning(false)}}return <><div className="section-head"><div><div className="eyebrow">PUBLICATION RECONCILIATION</div><h2>Local-first synchronization</h2><p>International connectors are optional. Core reconciliation works with available local records.</p></div><button className="primary" onClick={run}>{running?"Reconciling…":"Run reconciliation"}</button></div><div className="cards"><Card n="23" l="Local records"/><Card n="17" l="Matched"/><Card n="4" l="Metadata conflicts"/><Card n="2" l="Potentially missing"/></div><Panel title={live.length?"Live reconciliation results":"Reconciliation candidates"}>{(live.length?live:[{left_record_id:"PUB-1042",title_similarity:.987,author_similarity:1},{left_record_id:"PUB-1077",title_similarity:.934,author_similarity:1},{left_record_id:"PUB-1091",title_similarity:.712,author_similarity:1}]).map((r:any)=><div className="recon" key={r.left_record_id}><div><b>{r.left_record_id}</b><span>Title similarity · {Math.round(r.title_similarity*1000)/10}%</span></div><strong>Author {Math.round(r.author_similarity*100)}%</strong><span className="pill">{r.title_similarity>.95?"MATCH":r.title_similarity>.8?"REVIEW":"CONFLICT"}</span><button>Compare</button></div>)}</Panel></>}
function Review(){return <><div className="section-head"><div><div className="eyebrow">HUMAN REVIEW</div><h2>Evidence before decision</h2><p>AI produces flags and evidence; authorized staff make the final decision.</p></div></div><Panel title="Review queue"><div className="review-banner">Human validation required for every consequential screening decision.</div>{["NRIF-2026-014 · Duplicate candidate","NRIF-2026-016 · Eligibility criterion","PUB-1077 · Author entity match"].map((x,i)=><div className="review-row" key={x}><div><b>{x}</b><small>{["2 supporting sources","1 rule + page evidence","3 matched author fields"][i]}</small></div><button>Review evidence</button></div>)}</Panel></>}
function Integrations({org}:{org:any}){return <><div className="section-head"><div><div className="eyebrow">INTEGRATIONS</div><h2>{org.name}</h2><p>Configure connectors without changing the AI/ML core.</p></div><button className="primary">+ Add connector</button></div><div className="grid">{org.sources.map((s:string)=><div className="panel connector" key={s}><div><span className="connector-icon">↔</span><h3>{s}</h3><small>Connector ready for authorized data</small></div><span className="status">● Available</span><button>Configure</button></div>)}</div></>}
